name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^10.3 || ^11
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2025-10-24
version: '2.1.15'
project: 'eca'
datestamp: 1761318769
